version: '2'

services:

  arduino_ci:
    build:
      context: .
      dockerfile: arduino-ci.Dockerfile
    volumes:
      - .:/home/work
    command: bash ./scripts/testAndBuild.sh
    tty: true
    container_name: arduino_ci
